/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.supermarket.view;

import br.com.supermarket.dao.ConexaoDB;
import br.com.supermarket.dao.ProdutoDAO;
import br.com.supermarket.model.Produto;
import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class RelatorioSistema extends javax.swing.JFrame {
    String CLASS = "";

    /**
     * Creates new form RelatorioSistema
     */
    public RelatorioSistema() {
        initComponents();
        readJTableEstoque();
        publicaCbFuncProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbEstoque = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btReporEstoque = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbFuncProd = new javax.swing.JTable();
        txtPesquisar1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbFiltroFuncProd = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFuncProd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios do Sistema");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(50, 185, 170));

        jButton3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/zoom.png"))); // NOI18N
        jButton3.setText("Checar");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/bin.png"))); // NOI18N
        jButton4.setText("Limpar");
        jButton4.setToolTipText("Limpar registros do histórico");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        taRelatorio.setColumns(20);
        taRelatorio.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        taRelatorio.setRows(5);
        taRelatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane5.setViewportView(taRelatorio);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("LOGs do sistema");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sistema", jPanel3);

        jPanel4.setBackground(new java.awt.Color(50, 185, 170));

        tbEstoque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbEstoque.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tbEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Qtde. estoque", "Qtde. min."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEstoqueMouseClicked(evt);
            }
        });
        tbEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbEstoqueKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tbEstoque);

        txtPesquisar.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtPesquisar.setToolTipText("Pesquisar Categoria");
        txtPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/zoom.png"))); // NOI18N

        btReporEstoque.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btReporEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/lorry_add.png"))); // NOI18N
        btReporEstoque.setText("Repor Estoque");
        btReporEstoque.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btReporEstoque.setPreferredSize(new java.awt.Dimension(150, 30));
        btReporEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporEstoqueActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setText("Estoque");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btReporEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btReporEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estoque", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        tbFuncProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbFuncProd.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        tbFuncProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFuncProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncProdMouseClicked(evt);
            }
        });
        tbFuncProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbFuncProdKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tbFuncProd);

        txtPesquisar1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtPesquisar1.setToolTipText("Pesquisar Categoria");
        txtPesquisar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPesquisar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisar1KeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/zoom.png"))); // NOI18N

        cbFiltroFuncProd.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        cbFiltroFuncProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbFiltroFuncProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroFuncProdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setText("Filtro");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setText("Análise de Vendas Funcionário/Produto");

        taFuncProd.setColumns(20);
        taFuncProd.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        taFuncProd.setRows(5);
        taFuncProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(taFuncProd);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFiltroFuncProd, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbFiltroFuncProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vendas", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lerRelatorio();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limparRelatorio();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        readJTableForDesk(txtPesquisar.getText());
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btReporEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporEstoqueActionPerformed
        if (tbEstoque.getSelectedRow() != -1) {
            
            Produto produtoEstoque = new Produto();

            produtoEstoque.setId((int)tbEstoque.getValueAt(tbEstoque.getSelectedRow(), 0));
            produtoEstoque.setNome(tbEstoque.getValueAt(tbEstoque.getSelectedRow(), 1).toString());
            produtoEstoque.setQuantidade((int)tbEstoque.getValueAt(tbEstoque.getSelectedRow(), 2));
            produtoEstoque.setQuantidadeMinimaEstoque((int)tbEstoque.getValueAt(tbEstoque.getSelectedRow(), 3));

            TelaReporEstoque telaReporEstoque = new TelaReporEstoque();
            telaReporEstoque.reporEstoque(produtoEstoque);
            telaReporEstoque.setVisible(true);
            
            readJTableEstoque();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o produto desejado", "Escolha uma opção", JOptionPane.WARNING_MESSAGE);
            tbEstoque.requestFocus();
        }
    }//GEN-LAST:event_btReporEstoqueActionPerformed

    private void tbEstoqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbEstoqueKeyReleased
        limparCampos();
        //eventoTabela();
    }//GEN-LAST:event_tbEstoqueKeyReleased

    private void tbEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEstoqueMouseClicked
        limparCampos();
        //eventoTabela();
    }//GEN-LAST:event_tbEstoqueMouseClicked

    private void tbFuncProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncProdMouseClicked
        eventoTabela();
    }//GEN-LAST:event_tbFuncProdMouseClicked

    private void tbFuncProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbFuncProdKeyReleased
        eventoTabela();
    }//GEN-LAST:event_tbFuncProdKeyReleased

    private void txtPesquisar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisar1KeyReleased

    private void cbFiltroFuncProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroFuncProdActionPerformed
        String escolha = cbFiltroFuncProd.getSelectedItem().toString();       
        filtroFuncProd(escolha);
    }//GEN-LAST:event_cbFiltroFuncProdActionPerformed

    public void limparCampos() {
        taRelatorio.setText("");
    }

    public void lerRelatorio() {
        limparCampos();
        String arquivoRelatorio = (new File("Relatorio_Login-Logout.txt").getAbsolutePath());
        String texto = "";
        try (BufferedReader br = new BufferedReader(new FileReader(arquivoRelatorio))) {
            String sCurrentLine;
            while ((sCurrentLine = br.readLine()) != null) {
                texto += sCurrentLine + "\n";
            }
            taRelatorio.setText(texto);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao ler Relatório", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparRelatorio() {
        limparCampos();
        try {
            String arquivoRelatorio = (new File("Relatorio_Login-Logout.txt").getAbsolutePath());
            FileWriter out = new FileWriter(arquivoRelatorio);
            out.write("");
            out.close();
            JOptionPane.showMessageDialog(null, "Relatório do sistema limpo", "Limpo!", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(TelaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao limpar o Relatório", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void readJTableEstoque() {
        DefaultTableModel modelo = (DefaultTableModel) tbEstoque.getModel();
        modelo.setNumRows(0);
        ProdutoDAO produtoDAO = new ProdutoDAO();
        for (Produto produto : produtoDAO.read()) {
            modelo.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getQuantidade(),
                produto.getQuantidadeMinimaEstoque()
            });
        }
        validaTabela();
    }
    
    public void readJTableForDesk(String desc) {
        DefaultTableModel modelo = (DefaultTableModel) tbEstoque.getModel();
        modelo.setNumRows(0);
        ProdutoDAO produtoDAO = new ProdutoDAO();
        
        for (Produto produto : produtoDAO.readForDesc(desc)) {            
            modelo.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getQuantidade(),
                produto.getQuantidadeMinimaEstoque()
            });
        }
        validaTabela();
    }

    public void validaTabela() {
        tbEstoque.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value,
                        isSelected, hasFocus, row, column);
                
                Color c = Color.WHITE;
                Object minEstoque = tbEstoque.getValueAt(row, 3);
                Object estoque = tbEstoque.getValueAt(row, 2);
                if ((minEstoque != null && estoque != null) 
                        && Integer.parseInt(minEstoque.toString()) >= Integer.parseInt(estoque.toString())) {
                    c = Color.RED;
                }
                label.setBackground(c);
                tbEstoque.setSelectionForeground(Color.GREEN);
                    
                return label;
            }
        });
    }
    
    /* TELA FUNCIONÁRIO PRODUTO */
    String opSelect = "";
    public void publicaCbFuncProd() {
        String valorAcesso[] = {"Funcionario", "Produto"};
        for (int i = 0; i < valorAcesso.length; i++){
            cbFiltroFuncProd.addItem(valorAcesso[i]);
        }
    }
    
    public void filtroFuncProd(String escolha) {
        String sql = "";
        opSelect = escolha;
        if (escolha.equals("Funcionario")) {
            //System.out.println("Func");
            sql = "select id_funcionario, nome_funcionario from tb_funcionario;";
        } else if (escolha.equals("Produto")) {
            //System.out.println("Prod");
            sql = "SELECT id_produto, nome_produto FROM tb_produto";
        }
        
        Connection connection = ConexaoDB.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            stmt = connection.prepareStatement(sql);
            rs = stmt.executeQuery();
            
            DefaultTableModel modelo = (DefaultTableModel) tbFuncProd.getModel();
            modelo.setNumRows(0);
            
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt(1),
                    rs.getString(2)
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher formulário... " + e);
        } finally {
            ConexaoDB.closeConnection(connection, stmt, rs);
        }
    }
    
    private void eventoTabela() {
        if (tbFuncProd.getSelectedRow() != -1) {
            tbFuncProd.getValueAt(tbFuncProd.getSelectedRow(), 0).toString();
            tbFuncProd.getValueAt(tbFuncProd.getSelectedRow(), 1).toString();
            
            /* BUSCAR CAMPOS NO BANCO */
            String texto = "";
            int id = (int) tbFuncProd.getValueAt(tbFuncProd.getSelectedRow(), 0);
            Connection connection = ConexaoDB.getConnection();
            PreparedStatement stmt = null;
            ResultSet rs = null;
            try {
                if (opSelect.equals("Funcionario")) {
                    stmt = connection.prepareStatement("SELECT * FROM view_venda WHERE id_funcionario ='" + id + "' ORDER BY data_venda ASC");
                    rs = stmt.executeQuery();
                    //rs.first();
                    while (rs.next()) {
                        texto += "ID da Venda: " + (String.valueOf(rs.getInt(1)))+"\n";
                        texto += "Valor da Venda: " + (String.valueOf(rs.getDouble(2)))+"\n";
                        texto += "Data da Venda: " + (rs.getString(3))+"\n";
                        texto += "ID do Funcionário: " + (String.valueOf(rs.getInt(4)))+" - ";
                        texto += "Nome do Funcionário: " + (rs.getString(5))+"\n\n";
                    }
                } else if (opSelect.equals("Produto")) {
                    stmt = connection.prepareStatement("SELECT DISTINCT * FROM view_itensVenda WHERE id_produto ='" + id + "' ORDER BY data_venda ASC");
                    rs = stmt.executeQuery();
                    //rs.first();
                    while (rs.next()) {
                        texto +=  "ID da Venda: " + (String.valueOf(rs.getInt(1)))+"\n";
                        texto +=  "Data da Venda: " + (rs.getString(2))+"\n";
                        texto += "ID do Produto: " + (String.valueOf(rs.getString(3)))+" - ";
                        texto += "Nome do Produto: " + (rs.getString(4))+"\n";
                        texto += "Quantidade do Produto " + (String.valueOf(rs.getInt(5)))+"\n\n";
                    }
                }
                
                taFuncProd.setText(texto);
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao preencher formulário... " + e, "Erro", JOptionPane.ERROR_MESSAGE);
            } finally {
                ConexaoDB.closeConnection(connection, stmt, rs);
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReporEstoque;
    private javax.swing.JComboBox<String> cbFiltroFuncProd;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea taFuncProd;
    private javax.swing.JTextArea taRelatorio;
    private javax.swing.JTable tbEstoque;
    private javax.swing.JTable tbFuncProd;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPesquisar1;
    // End of variables declaration//GEN-END:variables
}
