/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.supermarket.view;

import br.com.supermarket.dao.VendaProdutoDAO;
import br.com.supermarket.model.Venda;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Gustavo
 */
public class TelaPagamento extends javax.swing.JFrame {
    
    Venda venda_concluida;
    boolean validaPagamento = false;
    double valorTotal = 0;
    
    public void limparCampos() {
        txtTotalPago.setText("");
        txtTroco.setText("");
        validaPagamento = false;
    }
    
    public void iniciaVenda(Venda venda) {
        venda_concluida = venda;
        txtTotal.setText(String.valueOf(String.format("%.2f", venda_concluida.getValorVenda())));
        btConcluirCompra.setEnabled(false);
    }

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        formaPagamento.add(rbDinheiro); formaPagamento.add(rbDebito); formaPagamento.add(rbCredito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        rbDinheiro = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalPago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btConcluirCompra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Venda - Pagamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel1.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbDinheiro.setBackground(new java.awt.Color(0, 153, 153));
        formaPagamento.add(rbDinheiro);
        rbDinheiro.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        rbDinheiro.setText("Dinheiro");
        rbDinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDinheiroMouseClicked(evt);
            }
        });

        rbDebito.setBackground(new java.awt.Color(0, 153, 153));
        formaPagamento.add(rbDebito);
        rbDebito.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        rbDebito.setText("Débito");
        rbDebito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDebitoMouseClicked(evt);
            }
        });

        rbCredito.setBackground(new java.awt.Color(0, 153, 153));
        formaPagamento.add(rbCredito);
        rbCredito.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        rbCredito.setText("Crédito");
        rbCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCreditoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel2.setText("Total Pago:");

        txtTotalPago.setEditable(false);
        txtTotalPago.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtTotalPago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotalPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalPagoKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel3.setText("Troco:");

        txtTroco.setEditable(false);
        txtTroco.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtTroco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btConcluirCompra.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btConcluirCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/accept.png"))); // NOI18N
        btConcluirCompra.setText("Concluir");
        btConcluirCompra.setToolTipText("Concluir");
        btConcluirCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btConcluirCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluirCompraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setText("Escolha o método de pagamento abaixo:");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setText("Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConcluirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rbCredito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbDebito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbDinheiro, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel4))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCredito)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btConcluirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
           
    private void btConcluirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluirCompraActionPerformed
        if (validaPagamento) {
            VendaProdutoDAO vendaProdutoDAO = new VendaProdutoDAO();
            vendaProdutoDAO.iniciaVenda(venda_concluida);
            imprimirNota();           
        } else {
            JOptionPane.showMessageDialog(null, "Valor insuficiente para concluir a compra", 
                    "Valor Insuficiente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btConcluirCompraActionPerformed

    
    /* IMPRIME */
    public void imprimirNota() {
        venda_concluida.setConteudo("\n\n\nTotal: " + venda_concluida.getValorVenda() + 
                "\n\nData: " + venda_concluida.getDataVenda() + "\n\n\n           Volte Sempre!!!       ");
        Document document = new Document();
        String nomeDoc = ("venda.pdf");
        
        try {
            PdfWriter.getInstance(document, new FileOutputStream(nomeDoc));            
            document.open();
            document.add(new Phrase(venda_concluida.getConteudo()));
            TelaVenda telaVenda = new TelaVenda();
            telaVenda.limparCampos();
            this.dispose();
        } catch (DocumentException | FileNotFoundException ex) {
            System.out.println("Erro: " + ex);
        } finally {
            document.close();
        }
        
        try {
            Desktop.getDesktop().open(new File(nomeDoc));
        } catch (IOException ex) {
            System.out.println("Erro: " + ex);
        }
    }    
    /* fim */
    
    private void rbDinheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDinheiroMouseClicked
        limparCampos();
        txtTotalPago.setEditable(true);
        btConcluirCompra.setEnabled(false);
        txtTotalPago.requestFocus();
    }//GEN-LAST:event_rbDinheiroMouseClicked

    private void rbDebitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDebitoMouseClicked
        debitoCredito();        
    }//GEN-LAST:event_rbDebitoMouseClicked

    private void rbCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCreditoMouseClicked
        debitoCredito();        
    }//GEN-LAST:event_rbCreditoMouseClicked

    private void txtTotalPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPagoKeyReleased
        validaPagamento = false;
        dinheiro();
    }//GEN-LAST:event_txtTotalPagoKeyReleased
    
    private void debitoCredito() {
        limparCampos();
        double troco = 0;
        txtTotalPago.setEditable(false); 
        txtTotalPago.setText(String.valueOf(venda_concluida.getValorVenda()));
        troco = (venda_concluida.getValorVenda() - venda_concluida.getValorVenda());
        txtTroco.setText(String.valueOf(String.format("%.2f", troco)));
        validaPagamento = true;
        btConcluirCompra.setEnabled(true);
    }
    
    private void dinheiro() {
        btConcluirCompra.setEnabled(true);
        if (txtTotalPago.getText().trim().isEmpty()) {
            txtTroco.setText("");
        } else {
            double troco = 0, totalPago = Double.valueOf(txtTotalPago.getText().toString().replace(",", "."));
            if (totalPago >= 0) {
                troco = totalPago - venda_concluida.getValorVenda();
                txtTroco.setText(String.valueOf(String.format("%.2f", troco)));
                if (totalPago >= venda_concluida.getValorVenda()) {
                    validaPagamento = true;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Informe valores positivos", "Valor Inválido", JOptionPane.ERROR_MESSAGE);
            txtTotalPago.setText("");
            }
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConcluirCompra;
    private javax.swing.ButtonGroup formaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JRadioButton rbDinheiro;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalPago;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
