/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.supermarket.view;


import br.com.supermarket.dao.VendaProdutoDAO;
import br.com.supermarket.model.Produto;
import br.com.supermarket.model.Venda;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class TelaVenda extends javax.swing.JFrame {

    Venda venda;
    //String conteudo = "";
    int qtde = 0;
    double prec = 0, total;
    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        limparCampos();
        txtCodigoBarras.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtTotal = new javax.swing.JLabel();
        btVender = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRemoveItem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Vendas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setText("Código de Barras");

        txtCodigoBarras.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtCodigoBarras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel2.setText("Quantidade");

        txtQuantidade.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtQuantidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTotal.setBackground(new java.awt.Color(0, 0, 0));
        txtTotal.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(153, 69, 24));

        btVender.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        btVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/money_dollar.png"))); // NOI18N
        btVender.setText("Finalizar Venda");
        btVender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons 1/add.png"))); // NOI18N
        jButton2.setText("Nova Venda");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbProdutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbProdutos.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Qtde.", "Produto", "Valor un."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbProdutos);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 69, 24));
        jLabel3.setText("TOTAL R$");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setText("Remover Item");

        txtRemoveItem.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        txtRemoveItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtRemoveItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemoveItemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(473, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(327, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btVender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void limparCampos() {
        venda = new Venda();
        DefaultTableModel modeloProduto = (DefaultTableModel) tbProdutos.getModel();
        modeloProduto.setNumRows(0);
        txtQuantidade.setText("");
        txtCodigoBarras.setText("");
        txtRemoveItem.setText("");
        txtTotal.setText("");
    }
    
    private void txtCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyReleased
        if ((txtCodigoBarras.getText().length() < 4) && (evt.getKeyCode() == KeyEvent.VK_ENTER)) { 
            txtQuantidade.setText(txtCodigoBarras.getText());
            txtCodigoBarras.setText("");
        } else if (txtCodigoBarras.getText().length() == 13 && (evt.getKeyCode() == KeyEvent.VK_ENTER)) {
            readJTableForDesk(txtCodigoBarras.getText());
            txtCodigoBarras.setText(""); 
            txtQuantidade.setText("");
        } else if (txtCodigoBarras.getText().length() > 13) {
            JOptionPane.showMessageDialog(null, "Código de Barras Inválido");
            txtCodigoBarras.setText("");
        }
    }//GEN-LAST:event_txtCodigoBarrasKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderActionPerformed
        if (this.venda.v1 == null || tbProdutos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Escolha produtos");
        } else {
            adicionaItem();
            /*VendaProdutoDAO vendaProdutoDAO = new VendaProdutoDAO();
            vendaProdutoDAO.iniciaVenda(venda);*/
            TelaPagamento telaPagamento = new TelaPagamento();
            telaPagamento.iniciaVenda(venda);
            telaPagamento.setVisible(true);
            //imprimirNota();
            //limparCampos();
        }
    }//GEN-LAST:event_btVenderActionPerformed

    private void txtRemoveItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemoveItemKeyReleased
        removeItem();
    }//GEN-LAST:event_txtRemoveItemKeyReleased
    
    public void readJTableForDesk(String desc) {
        DefaultTableModel modeloProduto = (DefaultTableModel) tbProdutos.getModel();
        VendaProdutoDAO vendaProdutoDAO = new VendaProdutoDAO();
        String nomeProduto, descricao = "", precoUnit = "";
        int prod_id = 0;
                
        for (Produto produto : vendaProdutoDAO.readForDesc(desc)) {
            prod_id = produto.getId();
            nomeProduto = produto.getNome();
            descricao = nomeProduto + " - " + produto.getMarca();
            precoUnit = String.valueOf(String.format("%.2f", produto.getValorVenda()));
        }
        
        if (txtQuantidade.getText().equals("")) {
            txtQuantidade.setText("1");
        }
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        
        modeloProduto.addRow(new Object[]{ prod_id, quantidade, descricao, precoUnit });
        calculaTotal();
    }
    
    private void calculaTotal() {
        total = 0;
        for (int i = 0; i <= tbProdutos.getRowCount()-1; i++) {
            qtde = Integer.parseInt(tbProdutos.getValueAt(i, 1).toString());
            prec = Double.parseDouble(tbProdutos.getValueAt(i, 3).toString().replace(",", "."));
            total += (qtde * prec);
        }
        //System.out.println("Total: " + total);
        txtTotal.setText(String.valueOf(String.format("%.2f", total)));
    }
    
    private void adicionaItem() {
        //int qtde = 0, id_prod = 0; 
        int id_prod = 0; 
        String nome_prod = "";
        
        for (int i=0; i <= tbProdutos.getRowCount()-1; i++) {
            Venda vendaLista = new Venda();
            id_prod = Integer.parseInt(tbProdutos.getValueAt(i, 0).toString());
            qtde = Integer.parseInt(tbProdutos.getValueAt(i, 1).toString());
            nome_prod = tbProdutos.getValueAt(i, 2).toString();
            prec = Double.parseDouble(tbProdutos.getValueAt(i, 3).toString().replace(",", "."));
                        
            //total += (qtde * prec);
            venda.setConteudo(id_prod + "      x      " + nome_prod + "   x   " + qtde + "   x " + prec + "\n");
            //System.out.println(tbProdutos.getValueAt(i, 0).toString() + nome_prod + tbProdutos.getValueAt(i, 1).toString() + tbProdutos.getValueAt(i, 3).toString() + "\n");
                        
            vendaLista.setId_produto(id_prod);
            vendaLista.setQtdeVendaProduto(qtde);
            
            venda.v1.add(vendaLista);
        }
        //System.out.println("qtde: " + qtde + "\nPrec: " + prec + "\ntotal: " + total);        
        venda.setValorVenda(total);
    }
    
    private void removeItem() {
        DefaultTableModel modeloProduto = (DefaultTableModel) tbProdutos.getModel();
        
        String cod = txtRemoveItem.getText().toString();
        for(int x = tbProdutos.getRowCount()-1; x >= 0; x--){
            String coluna = String.valueOf(tbProdutos.getValueAt(x, 0));
            if (coluna.equals(cod)) {
                //aqui vc pega o restante dos valores da linha
                prec = Double.parseDouble(tbProdutos.getValueAt(x, 3).toString().replace(",", "."));                
                total -= prec;
                modeloProduto.removeRow(x);
                //System.out.println("Valor de x: " + x);
            }
        }
        calculaTotal();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVender;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtRemoveItem;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
